services:
  - type: web
    name: opencart
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PHP_VERSION
        value: 8.2
      - key: APP_ENV
        value: production
    healthCheckPath: /index.php

databases:
  - name: opencart-db
    plan: free
    databaseName: opencart
    user: opencart

